### ISSUE TITLE
adding a compiled example of LDM-nnn.pdf

### ISSUE THREAD

**Issue by suberlak** [lsst/lsst-texmf#16]
Hi! 

I tried to add a compiled example of LDM-nnn.pdf   to the examples folder ,  but I have no write access.  It would really help to rename it as  Example_doc_LDM.tex,  and Example_doc_LDM.pdf  . The other files are labeled as examples and I looked for a while for an example of a document rather than a presentation.  It also took  4 people in my department to figure out that the texmf directory from your repo has to be put  to  ~/Library/texmf,   making sure that kpsewhich -var-value TEXMFHOME   points to ~/Library/texmf.    It is highly nontrivial   if one has never done anything like that ,  and I suggest putting this information on the front page .  

Best wishes
Chris

**Comment by timj** [comment]
I've added "Data Management" team to this repo so you should be able to make a pull request now.

I specifically don't want compiled PDFs in the repo as it will balloon the size of the repository given an entirely new commit is required each time. I'd like the PDFs that get built by Travis to be persisted somewhere and I should talk to @jonathansick about that.

I  will think about renaming the example. The `Example_...` naming convention came after I had made the LDM example. I thought that `examples/LDM...` made it clear it was an example LDM but maybe that's because I already know what an LDM is. I don't really think that `example/Example...` adds any clarity but I'll take another look.

Also, I'm not sure I understand your compilation issue. Setting `$TEXMFHOME` to `~/wherever/lsst-texmf/texmf` is all that is needed to get things to work for me. It doesn't need to be installed into `~/Library`. I'll update the README to suggest `$TEXMFHOME` rather than `$TEXMFLOCAL` but they are more or less the same if neither have been set previously.

**Comment by jonathansick** [comment]
I like the idea of having Travis build the examples and publish example products + documentation (essentially the README) on lsst.io — `lsst-texmf.lsst.io` maybe?

Not only will that keep pdfs out of the repo, it'll also add continuous integration that ensures the examples build.

**Comment by timj** [comment]
They already build, but they aren't persisted. Master is protected and PRs are only allowed if Travis passes.

**Comment by suberlak** [comment]
Hi!

the compilation issue is that 1) simple google search didn't say where to find $TEXMFHOME ,  2) even with the  kpsewhich -var-value TEXMFHOME  I still don't know how to change it - it seems that it only displays its value.  It would be helpful to show on the main page where the $TEXMFHOME is located, and how to change it (not in all cases, but at least one working example. Otherwise it's very confusing about what to do - 2 ppl I asked gave up). 

Best wishes
Chris

**Comment by timj** [comment]
```
export TEXMFHOME=`pwd`/lsst-texmf/texmf
```
works (assuming you are in the directory containing the clone). It's a normal environment variable that you set to tell tex where to find additional latex files.

**Comment by timj** [comment]
http://tex.stackexchange.com/questions/30494/how-to-make-latex-see-local-texmf-tree is quite informative. `kpsewhich -var-value TEXMFHOME` tells you where home currently is, but it can be overridden by setting the environment variable of the same name. My default is `~/Library/texmf` but I don't install `lsst-texmf` in there and override it. You should be able to soft link the `texmf` subdirectory of your `lsst-texmf` clone to `~/Library/texmf` without setting the environment variable.

**Comment by suberlak** [comment]
Thank you!   If I go to the directory  containing the clone ,  
`export TEXMFHOME=`pwd`/lsst-texmf/texmf/`   works.  Now the    
`kpsewhich -var-value TEXMFHOME`   yields 
/Users/chris/.....  /lsst-texmf/texmf/

**Comment by timj** [comment]
I'm actively writing documentation for these classes. I'll link the relevant PR when it turns up.

**Comment by timj** [comment]
@suberlak I've started on some user documentation. You can find a draft in #17 in file `docs/index.rst`.

**Comment by timj** [comment]
@suberlak are you okay with the new documentation I added as part of #17?

**Comment by suberlak** [comment]
What should I look at ? I can't find where the docs are  - there is a lot of code here  but where are the docs ?  https://github.com/lsst/lsst-texmf/pull/17/files   ?

**Comment by timj** [comment]
See https://github.com/lsst/lsst-texmf/blob/master/docs/index.rst (I've merged them now). They are readable there, although the rendered version isn't available yet (unless you build it yourself -- which you can do if you have the infrastructure installed for building a tech note).

**Comment by suberlak** [comment]
Ok, looks good, but I would add examples of what each citing command does (difference between \citell  or \citellp ? -  what would it look like in the compiled doc.) . For instance, I was looking for how to use in this  template  a citation  'Sesar+2010 did'  rather than   ' [2]  did '  ...  Is it possible ?

**Comment by timj** [comment]
Thanks. I will try to add some more detail. This conversation has finally led me to understand why `citell` is called `citell`. It stands for "cite livelink" and is for citing LiveLink documents. In our case it's used for citing DocuShare documents (and maybe DMTNs). Use `\citell` for LSST documents that have a DocuShare handle such as LDM-151 and LSE-163. `\citellp` is the same as `citell` but you end up with `[LDM-151]` (parens) rather than `LDM-151`. Use `\citep` for all other citations and it seems that the LSST style is numbers rather than AuthorYear (the class loads `natbib` with the `numbers` option). I'm not entirely sure if we explicitly chose that form but that's where we've ended up. In theory we could have AuthorYear style for LDM and numbers for LSE but I'm not sure how quickly we could reach consensus on that. Regardless, LDM-151 should always be referenced as `citell` or `citellp`. Maybe @jdswinbank, @ktlim or @womullan have an opinion on numbers vs author year.

**Comment by jonathansick** [comment]
Could we rename (or alias) `\citell` to `\cited` to stand for "cite document," which makes sense in the LSST context?

**Comment by timj** [comment]
Take a look at #21.

**Comment by suberlak** [comment]
Looks good, thanks for the examples, now I see that I can just customize the citation if I really need (for the sake of flow) for one citation to depart from the overall scheme  ( eg. 
` \citep[Sesar+2010]{sesar2010}  wrote `
to get    'Sesar+2010 wrote'   if I correctly understand ? )

**Comment by timj** [comment]
I think you'll end up with `[Sesar+2010 4]` if you do that (`\citep` will still show the reference number).  You might have to write
```latex
Sesar+2010 \nocite{sesar2010}
```
(please note we have a preference for using ADS bibcode keys rather than ambiguous authorYear keys).

Are you working on a DM tech note or an LDM? We might want a more compact option in the class for latex tech notes (which we can probably switch to automatically if the doc handle starts with DMTN).

**Comment by suberlak** [comment]
I'm working on DM tech notes for PDAC https://github.com/lsst-dmsst/PDAC_report  . There are not many references, but it affects how I write it, so it would be helpful if I could use the ApJ bibliography style ... Having  'in  Sesar et al. 2010'  rather than  'in Sesar et al. 2010 [2]'  would be nice (less cluttered) - like here https://github.com/suberlak/CRTS_paper/blob/master/main.pdf  . Especially that then the entire 'Author et al. Year ' links to the appropriate reference...

**Comment by suberlak** [comment]
Ps. So does   'a preference for using ADS bibcode keys'  mean that instead of using https://github.com/lsst-dmsst/PDAC_report/blob/master/references.bib  I should use something else ?

**Comment by timj** [comment]
Ok. You are blazing a trail writing a tech note in latex rather than restructured text.  I actually prefer AuthorYear citations so I am sympathetic to your plight. I wouldn't necessarily object to having this be configurable with a class option if you wanted to do a PR. For example,

```latex
\documentclass[authoryear,toc,lsstdraft]{lsstdoc}
```
As it should be pretty easy to adjust the `natbib` import to suit (an alternate `test-bibtex.tex` demonstrating it working would be great).

My comment regarding references is that we aim to generate a master bibliography file. Once documents are approved. References available from ADS will end up in https://github.com/lsst/lsst-texmf/blob/master/texmf/bibtex/bib/refs_ads.bib and we expect the keys in those references to be ADS bibcodes. For example `2010ApJ...717..133S` and not `Sesar2010`. AuthorYear cite keys are really confusing once you have people writing more than one paper a year. It's best to start off using ADS bibcode keys from the beginning rather than porting over later.

As you develop you can have your local references and `refs_ads` and `lsst` listed in your bibliographies and items will be picked up correctly.

Please get a DMTN number issues so you can name things properly (and preferably rename your repo). Before you do that though, I think there may be a problem with the automated DMTN issuing if your repo is not on in the `lsst-dm` org. We had not really envisaged DM tech notes being shared between two Github orgs. We were relying on Github not letting you create a repo with the same name in the same org but now someone could create DMTN-043 in lsst-dm even though you already created one in lsst-dmsst org. @athornton am I correct in saying this will be broken?

**Comment by mjuric** [comment]
@timj, @suberlak : I think Chris is mostly interested in using the right template right now; the DMTN number is less important (we can have that at the very end, especially if it's not supported).

I'm worried about the requirement for the tech note source to be by itself in its own repository; the note may depend on figures generated by some code or notebooks related to a larger analysis (e.g., https://github.com/lsst-dmsst/hybrid_focal_plane) and may naturally "sit" together with the code and data (e.g., as a subdirectory). Should we instead link it as a submodule (or via EUPS)? What's the best practice to follow?

**Comment by jonathansick** [comment]
I'm about to start a month-long sprint for Architecture to improve the tech note platform and implement LaTeX-based technotes specifically. If mixing multiple documents in a single Git repository is a requirement, and @timj gives me the go-ahead, I can implement a solution.

The one document-per-repo design comes from LSST the Docs, as it simplifies the versioning and deployment of individual documents.

Submodules would be one way of doing this with minimal changes to LSST the Docs itself. There might be some developer experience issues to test though.

Another way would be to extend LSST the Docs so that multiple projects can exist in sub-directories of a project repository. This would mean that all documents in a project would be versioned and deployed together. I'd also have to change how document numbers are issued and tracked.

**Comment by ktlim** [comment]
It seems to me that notebooks and figure-generating code should either be subsidiary to the report (i.e. live in its repo) or a specific version of them should be pointed to by the report (i.e. live in a separate repo with the report containing a pointer to a particular version).  Storing and versioning them all together when the code/notebooks/data might change for the purposes of the "larger analysis" (without a report update) seems inappropriate.

**Comment by jonathansick** [comment]
I like the idea of the shared analysis code being a versioned dependency of a document Git repository. I guess submodes or EUPS is the question, then. I've resisted using EUPS as the dependency manger, but I guess that could be a good solution if the analysis code is itself EUPS managed (i.e., part of, or a user of, the DM Stack).

**Comment by timj** [comment]
This ticket is going off topic. I'm perfectly happy with submodules for this sort of thing. The git repo with the report then points to a specific version that you can click through to without requiring an installation of eups (you can click through on Github as well and end up at the right place). I'm not entirely sure what's wrong with the notebooks being in an `_` subdirectory of the document. We've done that for other DMTNs.

**Comment by timj** [comment]
Figure generation code should surely be in the repo with the documents? Unless there's shared code generating figures for different reports. Then I'd use a git submodule, especially if the figures themselves aren't built as part of the document build (but are committed to the doc repo, not the code generation repo so the document can build standalone).

**Comment by timj** [comment]
For reference, DMTN-006, DMTN-007, DMTN-017 and LDM-513 store notebooks with their tech note content. The main problem is that each document puts the notebooks in a different part of the tree: `notebooks/`, `_notebooks/`, `code/notebooks/`, `DCR test code/` and `./`.
